CREATE TABLE KHACHHANG
(
	MaKH INT IDENTITY(1,1),
	HoTen NVARCHAR(50) NOT NULL,
	Taikhoan VARCHAR(50) UNIQUE,
	Matkhau VARCHAR(50) NOT NULL,
	Email VARCHAR(100) UNIQUE,
	DiachiKH NVARCHAR(200),
	DienthoaiKH VARCHAR(50),
	Ngaysinh DATETIME
	CONSTRAINT PK_Khachhang PRIMARY KEY(MaKH)
)

CREATE TABLE CHUDE
(
	MaCD INT IDENTITY(1,1),
	TenChuDe NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_ChuDe PRIMARY KEY(MaCD)
)

CREATE TABLE NHAXUATBAN
(
	MaNXB INT IDENTITY(1,1),
	TenNXB NVARCHAR(50) NOT NULL,
	Diachi NVARCHAR(200),
	DienThoai VARCHAR(50),
	CONSTRAINT PK_NhaXuatBan PRIMARY KEY(MaNXB)
)

CREATE TABLE SACH
(
	Masach INT IDENTITY(1,1),
	Tensach NVARCHAR(100) NOT NULL,
	Giaban DECIMAL(18,0) CHECK (Giaban>=0),
	Mota NVARCHAR(Max),
	Anhbia VARCHAR(50),
	Ngaycapnhat DATETIME,
	Soluongton INT,
	MaCD INT,
	MaNXB INT,
	CONSTRAINT PK_Sach PRIMARY KEY(Masach),
	CONSTRAINT FK_Chude FOREIGN KEY(MaCD) REFERENCES CHUDE(MaCD),
	CONSTRAINT FK_NhaXB FOREIGN KEY(MaNXB) REFERENCES NHAXUATBAN(MANXB)
)

CREATE TABLE TACGIA
(
	MaTG INT IDENTITY(1,1),
	TenTG NVARCHAR(50) NOT NULL,
	Diachi NVARCHAR(100),
	Tieusu NVARCHAR(Max),
	Dienthoai VARCHAR(50),
	CONSTRAINT PK_TacGia PRIMARY KEY(MaTG)
)CREATE TABLE VIETSACH(	MaTG INT,	Masach INT,	Vaitro NVARCHAR(50),	Vitri NVARCHAR(50),	CONSTRAINT PK_VietSach PRIMARY KEY(MaTG, Masach),	CONSTRAINT FK_TacGia FOREIGN KEY(MaTG) REFERENCES TACGIA(MaTG),	CONSTRAINT FK_Sach FOREIGN KEY(Masach) REFERENCES SACH(Masach))CREATE TABLE DONDATHANG
(
	MaDonHang INT IDENTITY(1,1),
	Dathanhtoan BIT,
	Tinhtranggiaohang BIT,
	Ngaydat DATETIME,
	Ngaygiao DATETIME,
	MaKH INT,
	CONSTRAINT FK_KhachHang FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
	CONSTRAINT PK_DonDatHang PRIMARY KEY (MaDonHang)
)CREATE TABLE CHITIETDONTHANG
(
	MaDonHang INT,
	Masach INT,
	Soluong INT CHECK(Soluong>0),
	Dongia DECIMAL(18,0) CHECK(Dongia>=0),
	CONSTRAINT PK_CTDatHang PRIMARY KEY(MaDonHang, Masach),
	CONSTRAINT FK_Donhang FOREIGN KEY (MaDonHang) REFERENCES DONDATHANG(MaDonHang),
	CONSTRAINT FK_Sach_CTDH FOREIGN KEY (Masach) REFERENCES SACH(Masach)
)

CREATE TABLE ADMIN
(
	UserAdmin varchar(30) primary key,
	PassAdmin varchar(30) not null,
	Hoten nvarchar(50)
)

Insert into Admin values('admin','123',N'Huỳnh Võ Tuấn Linh')
Insert into Admin values('user','123',N'Optimus')